- name: create directory cluster install
  become: yes
  become_user: "{{ privileged_user }}"
  become_method: "{{ becomemethod }}"
  file:
    path: "/home/{{ privileged_user }}/{{ cluster_id }}/installocpv4"
    state: directory
    mode: u=rwx,g=r,o-rwx
    owner: "{{ privileged_user }}"
    group: "{{ privileged_group }}"

- name: copy cluster install config  zip file into place
  become: yes
  become_user: "{{ privileged_user }}"
  become_method: "{{ becomemethod }}"
  copy:
    src: ../../../../../{{ cluster_id }}/config/install-config.yaml
    dest: /home/{{ privileged_user }}/{{ cluster_id }}/installocpv4/install-config.yaml
    owner: "{{ privileged_user }}"
    group: "{{ privileged_group }}"
    mode: u=rw,g-rwx,o-rwx
    force: yes

- name: replace pullSecret in install config
  become: yes
  become_user: "{{ privileged_user }}"
  become_method: "{{ becomemethod }}"
  vars:
      cluster_pullsecret: "{{ pullsecret | replace('\n', '') }}"
  replace:
    path: /home/{{ privileged_user }}/{{ cluster_id }}/installocpv4/install-config.yaml
    regexp: 'PULLSECRET'
    replace: "{{cluster_pullsecret|to_json}}"

- name: copy install script into place
  become_user: "{{ privileged_user }}"
  become_method: "{{ becomemethod }}"
  copy:
    src: "../../../../../scripts/install_ocpv4.sh"
    dest: "/home/{{ privileged_user }}/{{ cluster_id }}/install_ocpv4.sh"
    owner: "{{ privileged_user }}"
    group: "{{ privileged_group }}"
    mode: u=rwx,g-rwx,o-rwx
    force: yes

- name: run ocpv4 install script
  become: yes
  become_user: "{{ privileged_user }}"
  become_method: "{{ becomemethod }}"
  shell: "bash /home/{{ privileged_user }}/{{ cluster_id }}/install_ocpv4.sh {{ cluster_id }} {{ privileged_user }} {{ ocpv4_version }}"
  async: 21600
  poll: 30

- name: remove install config
  become: yes
  become_user: "{{ privileged_user }}"
  become_method: "{{ becomemethod }}"
  file:
    path: "/home/{{ privileged_user }}/{{ cluster_id }}/installocpv4/install-config.yaml"
    state: absent
