apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: stable-4.10
  startingCSV: 'odf-operator.v4.10.2'
  installPlanApproval: Manual
  name: odf-operator
  source: patch-via-overlay
  sourceNamespace: openshift-marketplace
