apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ocs-operator
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: stable-4.8
  installPlanApproval: Automatic
  name: ocs-operator
  source: patch-via-overlay
  sourceNamespace: openshift-marketplace
