apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: internalregistry
  namespace: openshift-image-registry
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-storagecluster-cephfs
