kind: Secret
apiVersion: v1
metadata:
  name: init-config-bundle-secret
  namespace: quay-enterprise
  annotations:
    argocd.argoproj.io/sync-wave: "2"
data:
  config.yaml: RkVBVFVSRV9VU0VSX0lOSVRJQUxJWkU6IHRydWUKQlJPV1NFUl9BUElfQ0FMTFNfWEhSX09OTFk6IGZhbHNlClNVUEVSX1VTRVJTOgotIHF1YXlhZG1pbgpGRUFUVVJFX1VTRVJfQ1JFQVRJT046IGZhbHNlCiNBTExPV19QVUxMU19XSVRIT1VUX1NUUklDVF9MT0dHSU5HOiBmYWxzZQojQVVUSEVOVElDQVRJT05fVFlQRTogRGF0YWJhc2UKI0RFRkFVTFRfVEFHX0VYUElSQVRJT046IDJ3CiNFTlRFUlBSSVNFX0xPR09fVVJMOiAvc3RhdGljL2ltZy9xdWF5LWhvcml6b250YWwtY29sb3Iuc3ZnCiNGRUFUVVJFX0JVSUxEX1NVUFBPUlQ6IGZhbHNlCiNGRUFUVVJFX0RJUkVDVF9MT0dJTjogdHJ1ZQojRkVBVFVSRV9NQUlMSU5HOiBmYWxzZQojUkVHSVNUUllfVElUTEU6IFF1YXkKI1JFR0lTVFJZX1RJVExFX1NIT1JUOiBRdWF5CiNTRVRVUF9DT01QTEVURTogdHJ1ZQojVEFHX0VYUElSQVRJT05fT1BUSU9OUzoKIy0gMncKI1RFQU1fUkVTWU5DX1NUQUxFX1RJTUU6IDYwbQojVEVTVElORzogZmFsc2UK
type: Opaque
