apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml 
- acm-channel-namespace.yaml
- subscription.yaml
- operatorgroup.yaml
- mch-crd-wait-job.yaml
- subscription-admin-rbac.yaml
- multiclusterhub.yaml
- channelrepo.yaml
