kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'open-cluster-management:subscription-admin'
  annotations:
      argocd.argoproj.io/sync-wave: "4"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:subscription-admin
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: kube:admin 
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: system:admin 
