apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../basecommon
- ../../basehub

patches:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: openshift-gitops-operator
      namespace: openshift-operators
    patch: |-
      - op: replace
        path: /spec/source
        value: 'redhat-operators'
