apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-operator
  namespace: openshift-operators-redhat
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  channel: "stable"
  startingCSV: 'elasticsearch-operator.5.4.2'
  name: elasticsearch-operator
  source: patch-via-overlay 
  sourceNamespace: openshift-marketplace
  installPlanApproval: Manual
  config:
    nodeSelector:
      node-role.kubernetes.io/logging: ""
    tolerations:
    - key: node-role.kubernetes.io/logging
      effect: NoSchedule
      operator: Exists
