apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resourcequota-manager
  annotations:
    argocd.argoproj.io/sync-wave: "5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resourcequota-manager
subjects:
- kind: ServiceAccount
  name: openshift-gitops-gstnonprod-argocd-application-controller
  namespace: openshift-gitops-gstnonprod
- kind: ServiceAccount
  name: openshift-gitops-gstprod-argocd-application-controller
  namespace: openshift-gitops-gstprod

