---
apiVersion: v1
kind: Namespace
metadata:
  name: stackrox
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhacs-operator
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
