apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- log_machineset_private-us-east-1a.yaml
- log_machineset_private-us-east-1b.yaml
- log_machineset_private-us-east-1c.yaml

patchesJson6902:
- target:
    group: machine.openshift.io
    version: v1beta1
    kind: MachineSet
    name: dsulliva-hub01-log-private-us-east-1a
    namespace: openshift-machine-api
  path: patch-channel-private-us-east-1a.yaml
- target:
    group: machine.openshift.io
    version: v1beta1
    kind: MachineSet
    name: dsulliva-hub01-log-private-us-east-1b
    namespace: openshift-machine-api
  path: patch-channel-private-us-east-1b.yaml
- target:
    group: machine.openshift.io
    version: v1beta1
    kind: MachineSet
    name: dsulliva-hub01-log-private-us-east-1b
    namespace: openshift-machine-api
  path: patch-channel-private-us-east-1c..yaml
