apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace-rhacs-operator.yaml
- namespace-stackrox.yaml
- operatorgroup.yaml
- subscription.yaml
- acs-combined-odf-sc-wait-job.yaml
- acs-combined-crd-wait-job.yaml
- central.yaml
- securedcluster.yaml
