apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhacs-operator
  namespace: rhacs-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: latest
  installPlanApproval: Manual
  name: rhacs-operator
  source: patch-via-overlay
  sourceNamespace: openshift-marketplace
  startingCSV: 'rhacs-operator.v3.70.0'
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
    - key: node-role.kubernetes.io/infra
      effect: NoSchedule
      operator: Exists
