apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
