apiVersion: v1
#baseDomain: nasatam.support
baseDomain: sandbox517.opentlc.com
fips: false
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5+7ziIOlJyVfF0LWyGf4140LBtU3a3380N0mEbCzaHY6K+iiQK+fjbvhQhO3mj+pxnrNMK3eCzdKjYopBNIEVc9dC4vN7sYtROM1Sc3faYiBhKaa0SeAyeWX/oBKF3gziGeeqYUaAtZNTlo+eS68ZrEH7weeuCdTgxO/XsT86ijWX1mLzT3gYjvsLgfoBxhFlA4hr6Yl2JGj+5duqfn2in/Jgn26O1+2UBxQLM1nmTYGpVIcoSbrtMXmI5SLfn7LEFeuCeTgXzxwbbVvV2LLzax0wFkVzMXHZPJLWL1WqlXH7yao/iXrmTflkIxDa1xTqQLfI0j6pNPlCxGA2D2R8KWPeXmwNPz+jzz0kq6Fx1BYDYOws/t3zhSIhBsGDDpcC0YlHUO6cv+hDqYEgJhofxxZEC79CaDWDzYwGDyv5iLaKSi28sCIxih0oasj/4gmLMcyKu98e2sQwLVJO9PN6eHZHMRbV96V5evyrDXnKLTxHHkez9L3VDbBlCtnge13KiXuRD4VfWb+4/k9GQOVAKEO15j0Pll8Fv+G/ACX1MMyv8cYtQcCVkyu7wlEApLrsTRjBPRV4IwsmrHkC70/hs2g95GA0/2POuH0YN05bHdu+xlvahgXrtAhp3tWXuYsRUZBZfimqjd+nmewkyitY8osrlfNJ8NYycw/LukDVdw== dsulliva@fancy'
pullSecret: 'PULLSECRET'
controlPlane:
  hyperthreading: Enabled 
  name: master
  platform:
    aws:
      zones:
      - us-east-1a
      - us-east-1b
      - us-east-1c
      rootVolume:
        type: gp2
      type: m5.xlarge
  replicas: 3
compute: 
- hyperthreading: Enabled
  name: worker
  platform:
    aws:
      rootVolume:
        type: gp2
      type: m5.xlarge
      zones:
      - us-east-1a
  replicas: 1
metadata:
  name: dsulliva-hub01
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.31.0.0/16
platform:
  aws:
    region: us-east-1
    userTags:
      adminContact: dsulliva
    amiID: ami-0c72f473496a7b1c2
