apiVersion: v1
baseDomain: nasatam.support
fips: false
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCeDv8bR/y6W2gPonSUr9Vzn4YsxCm4d7yyODPGLinZooUbN9gvK3FAmOuamVgeF+nfrQv9wCPi7ifkFTIYi68G0SC77YYrrQXStUI2IvCZUXkBEO2B6H6PhQN//2FeXbV+2tx3OpAMt17DKhIWtbrAkNLo/Ra7SL9zO4c9RvRehnh/FpWQGRfY3djtEl+PrwG+Vbdt1by4e0v4MLO7CIaIuT0Mf4siuU33NGS81kIU5x82mXkpVHjslwcLqpr5E/L1qCWX6SJ3cgiGD9PvgCL1alvBKoPxhgkjMzcvUX2tuWFWpehqswblGb9UBOCOdPUg67CJjzYWSdNmApZzuSvmi3DOCrSidHGqqXbfcRSfluti3yQi7bbxDfBXbxN08iXHZjJke9GNPKNbhsKyvMnI5MY1X9oeUNIewSYbqykflyfjorOdirWBpgaGL/sCqQcvjytterLtLCGZjtLaYWPZfZLRluY8XEhQ7tGelXlf6JWT5YaTfqVZifpON25NQIYYKkivKcSeIBoH6tUaB+ggDdnuI2xT9i/uKIjMtoOOwMxfagIgRj1hkgbb29m8qj1nlBuGccDP/1bkVEMpt1JKXuCjvO6jxh+ncM6bGeRT8dcy6i7iPv4tI3n+H0qJ+mwbdYZRwozk7xcO39tDxe3ydCzfoKWbK0Qr2Jb7cn4tvQ== ec2-user@ip-172-31-51-30.ec2.internal'
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3JobnN1cHBvcnRkc3VsbGl2YTF1d3BneTNxeG02b3h4ZDB2em5la3pkZXh2MTpWOU5WSVdTSFYxMU42TkhNNVkxWVpITFVNNTFEWjA3SElYNElZRUpNQUgzSDFVRE1NUkFaUjdBOVlUTUVKWVo2","email":"dsulliva@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3JobnN1cHBvcnRkc3VsbGl2YTF1d3BneTNxeG02b3h4ZDB2em5la3pkZXh2MTpWOU5WSVdTSFYxMU42TkhNNVkxWVpITFVNNTFEWjA3SElYNElZRUpNQUgzSDFVRE1NUkFaUjdBOVlUTUVKWVo2","email":"dsulliva@redhat.com"},"registry.connect.redhat.com":{"auth":"NjA3NTI1OHx1aGMtMVVXUEdZM1FYbTZvWFhkMFZ6bkVrekRFWFYxOmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lKbU1HTmpaakZrTVRFME1tTTBPVEV3WWpObU1tSTVaV1F3WmpVek1Ua3pZeUo5LnRzZ204ZVNEVkVmcDI5YlhXUFBqVG5VS3ZqUkUxTlVadE81WjJyNG9NSXVPQlR0RDZ0RDhnSU1ydDViZWU1WEpRSTZyMmVzNVlHMFg3c2NhaTRSZjRxLUNJY3RaUzQxQW9kN3N4YnFGTUF3WW9YUEZSTDlVUHZMMHFvTFBNbkNRamN3dlJ1eWJ1V0V4bE5nRmU3UXAwaE5rdGFvSXlOTkJpZkFvQ3BaaFRKM0dmallMTEtBdmtiZEE5a0NCc1lxRXJ0bmJXdnF1X0h2aG5ndU14WkRoQ0dOV0ZSaHd4Y2hQc0ZpQWRyMWNYQnViR3lsWlMySERqY2ktN2lDTDhwTS1tWHl0LXlVR1UzdGxIQWM3WDVCX2FDU1M3Y1Q5SzRIcks2Z05CNUdMQjV2Y1FwSS1FQXo2NlpPVWczR2FhMDA1VjBkVXJBVGl1ZG1VZllPelM4NzUxNTN3TVRRbW9hV2dnRmU4Nm96VERFRG9iTVZpMkF5UmlQT0JleXFHYVFaWm5FVGJQQkU2WlZ5NGI3UkQxb3EwQ29jMm5RNkgzYy1HRFBiQ3ZhRXNFWk0yQ3o0NE1NVEU5VXhmd3lRbFZyYXh6SndMZjh1aXJwUHJDVEpVNGRoeDd2NE1TUWZ3bndGYVU4Yk1OY1JZdkI1eWpGY3ZOS2dkMmduNjR6T3ZuMUlrYUhVLU12QUY5QXpPbmNtNjc5cTNqM1Jfa3pRbjVmVEZCX3pNSS1xcEtnTG8yb2JPMWx4bFdwcnlmcVZLNnY2eC1LTWZiN21zekxqY3d6YXdqWGZxdE54XzdhOGlRU19xRkJNbVZPaVM5cTdqUFVxUUdvQkRvLUlsV2Ixc3pES2NPaTI3ZEo0Y0dzTDJZeERtNGZTZ2kzQWtzMk9yWDhnY0Rqd0cxOFRPNEFN","email":"dsulliva@redhat.com"},"registry.redhat.io":{"auth":"NjA3NTI1OHx1aGMtMVVXUEdZM1FYbTZvWFhkMFZ6bkVrekRFWFYxOmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lKbU1HTmpaakZrTVRFME1tTTBPVEV3WWpObU1tSTVaV1F3WmpVek1Ua3pZeUo5LnRzZ204ZVNEVkVmcDI5YlhXUFBqVG5VS3ZqUkUxTlVadE81WjJyNG9NSXVPQlR0RDZ0RDhnSU1ydDViZWU1WEpRSTZyMmVzNVlHMFg3c2NhaTRSZjRxLUNJY3RaUzQxQW9kN3N4YnFGTUF3WW9YUEZSTDlVUHZMMHFvTFBNbkNRamN3dlJ1eWJ1V0V4bE5nRmU3UXAwaE5rdGFvSXlOTkJpZkFvQ3BaaFRKM0dmallMTEtBdmtiZEE5a0NCc1lxRXJ0bmJXdnF1X0h2aG5ndU14WkRoQ0dOV0ZSaHd4Y2hQc0ZpQWRyMWNYQnViR3lsWlMySERqY2ktN2lDTDhwTS1tWHl0LXlVR1UzdGxIQWM3WDVCX2FDU1M3Y1Q5SzRIcks2Z05CNUdMQjV2Y1FwSS1FQXo2NlpPVWczR2FhMDA1VjBkVXJBVGl1ZG1VZllPelM4NzUxNTN3TVRRbW9hV2dnRmU4Nm96VERFRG9iTVZpMkF5UmlQT0JleXFHYVFaWm5FVGJQQkU2WlZ5NGI3UkQxb3EwQ29jMm5RNkgzYy1HRFBiQ3ZhRXNFWk0yQ3o0NE1NVEU5VXhmd3lRbFZyYXh6SndMZjh1aXJwUHJDVEpVNGRoeDd2NE1TUWZ3bndGYVU4Yk1OY1JZdkI1eWpGY3ZOS2dkMmduNjR6T3ZuMUlrYUhVLU12QUY5QXpPbmNtNjc5cTNqM1Jfa3pRbjVmVEZCX3pNSS1xcEtnTG8yb2JPMWx4bFdwcnlmcVZLNnY2eC1LTWZiN21zekxqY3d6YXdqWGZxdE54XzdhOGlRU19xRkJNbVZPaVM5cTdqUFVxUUdvQkRvLUlsV2Ixc3pES2NPaTI3ZEo0Y0dzTDJZeERtNGZTZ2kzQWtzMk9yWDhnY0Rqd0cxOFRPNEFN","email":"dsulliva@redhat.com"}}}'
controlPlane:
  hyperthreading: Enabled 
  name: master
  platform:
    aws:
      zones:
      - us-east-1a
      - us-east-1b
      - us-east-1c
      rootVolume:
        type: gp2
      type: m5.xlarge
  replicas: 3
compute: 
- hyperthreading: Enabled
  name: worker
  platform:
    aws:
      rootVolume:
        type: gp2
      type: m5.xlarge
      zones:
      - us-east-1a
  replicas: 1
metadata:
  name: dsulliva-hub01
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.31.0.0/16
platform:
  aws:
    region: us-east-1
    userTags:
      adminContact: dsulliva
    amiID: ami-0c72f473496a7b1c2
