apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- worker_machineset_private-us-east-1a.yaml

patchesJson6902:
- target:
    group: machine.openshift.io
    version: v1beta1
    kind: MachineSet
    name: dsulliva-hub01-worker-private-us-east-1a
    namespace: openshift-machine-api
  path: patch-channel-private-us-east-1a.yaml
