apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-logging
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: gitops/manifests/openshift-logging/overlays/olmlocal-dsulliva-hub01
    repoURL: git@github.com:sullyvon/ocpv4-deployment-tam.git
    targetRevision: dsulliva-spoke_master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
