---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  platform:
    architectures:
      - "amd64"
  additionalImages:
    - name: registry.redhat.io/openshift4/ose-cli:v4.10.0-202205190747.p0.g878f5a8.assembly.stream
